{% set name = "babelizer" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/babelizer/archive/v{{ version }}.tar.gz
  sha256: e3ba559b47784979bf3c9dcec16725307e9b12e5ca89bbcfc6d7b2baaf4ed3af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - babelize=babelizer.cli:babelize


requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - black
    - click
    - gitpython
    - pyyaml
    - tomlkit
    - isort >=5
    - cookiecutter

test:
  requires:
    - git
  imports:
    - babelizer
  commands:
    - babelize --version
    - babelize --help
    - babelize init --help
    - babelize update --help
    - babelize generate --help
    - babelize generate

about:
  home: https://github.com/csdms/babelizer
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Simple, fast, extensible JSON encoder/decoder for Python

  # The remaining entries in this section are optional, but recommended.
  description: |
    The babelizer is an easy-to-use command line tool that automatically
    wraps BMI libraries, written in C, C++ or Fortran, so that they can be
    imported and used as Python packages. Within Python, models,
    regardless of their core language, appear as classes that expose a
    BMI. Users are then able to run models interactively through the
    Python command line, through Python scripts or Jupyter Notebooks,
    and to use Python-based BMI tools such as the bmi-tester, pymt, or landlab.
  doc_url: https://github.com/csdms/babelizer
  dev_url: https://github.com/csdms/babelizer

extra:
  recipe-maintainers:
    - mcflugen
